[build]
  build = "npm run build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json" 